package pe.edu.unsch.entities;
// Generated 16/07/2019 01:54:40 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Option generated by hbm2java
 */
@Entity
@Table(name = "option", catalog = "divisimabd")
public class Option implements java.io.Serializable {

	private Integer idoption;
	private Submodule submodule;
	private String name;
	private Byte status;
	private Set<ProfileOption> profileOptions = new HashSet<ProfileOption>(0);

	public Option() {
	}

	public Option(Submodule submodule) {
		this.submodule = submodule;
	}

	public Option(Submodule submodule, String name, Byte status, Set<ProfileOption> profileOptions) {
		this.submodule = submodule;
		this.name = name;
		this.status = status;
		this.profileOptions = profileOptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idoption", unique = true, nullable = false)
	public Integer getIdoption() {
		return this.idoption;
	}

	public void setIdoption(Integer idoption) {
		this.idoption = idoption;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsubmodule", nullable = false)
	public Submodule getSubmodule() {
		return this.submodule;
	}

	public void setSubmodule(Submodule submodule) {
		this.submodule = submodule;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "option")
	public Set<ProfileOption> getProfileOptions() {
		return this.profileOptions;
	}

	public void setProfileOptions(Set<ProfileOption> profileOptions) {
		this.profileOptions = profileOptions;
	}

}
