package pe.edu.unsch.entities;
// Generated 16/07/2019 01:54:40 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Partner generated by hbm2java
 */
@Entity
@Table(name = "partner", catalog = "divisimabd")
public class Partner implements java.io.Serializable {

	private Integer idpartner;
	private String name;
	private Set<Product> products = new HashSet<Product>(0);

	public Partner() {
	}

	public Partner(String name, Set<Product> products) {
		this.name = name;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpartner", unique = true, nullable = false)
	public Integer getIdpartner() {
		return this.idpartner;
	}

	public void setIdpartner(Integer idpartner) {
		this.idpartner = idpartner;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
