package pe.edu.unsch.entities;
// Generated 16/07/2019 01:54:40 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", catalog = "divisimabd")
public class Profile implements java.io.Serializable {

	private Integer idprofile;
	private String name;
	private Set<AccountProfile> accountProfiles = new HashSet<AccountProfile>(0);
	private Set<ProfileOption> profileOptions = new HashSet<ProfileOption>(0);

	public Profile() {
	}

	public Profile(String name, Set<AccountProfile> accountProfiles, Set<ProfileOption> profileOptions) {
		this.name = name;
		this.accountProfiles = accountProfiles;
		this.profileOptions = profileOptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idprofile", unique = true, nullable = false)
	public Integer getIdprofile() {
		return this.idprofile;
	}

	public void setIdprofile(Integer idprofile) {
		this.idprofile = idprofile;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<AccountProfile> getAccountProfiles() {
		return this.accountProfiles;
	}

	public void setAccountProfiles(Set<AccountProfile> accountProfiles) {
		this.accountProfiles = accountProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<ProfileOption> getProfileOptions() {
		return this.profileOptions;
	}

	public void setProfileOptions(Set<ProfileOption> profileOptions) {
		this.profileOptions = profileOptions;
	}

}
