package pe.edu.unsch.entities;
// Generated 16/07/2019 01:54:40 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Submodule generated by hbm2java
 */
@Entity
@Table(name = "submodule", catalog = "divisimabd")
public class Submodule implements java.io.Serializable {

	private Integer idsubmodule;
	private Module module;
	private String name;
	private String url;
	private Byte status;
	private Set<Option> options = new HashSet<Option>(0);

	public Submodule() {
	}

	public Submodule(Module module) {
		this.module = module;
	}

	public Submodule(Module module, String name, String url, Byte status, Set<Option> options) {
		this.module = module;
		this.name = name;
		this.url = url;
		this.status = status;
		this.options = options;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsubmodule", unique = true, nullable = false)
	public Integer getIdsubmodule() {
		return this.idsubmodule;
	}

	public void setIdsubmodule(Integer idsubmodule) {
		this.idsubmodule = idsubmodule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmodule", nullable = false)
	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", length = 45)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "submodule")
	public Set<Option> getOptions() {
		return this.options;
	}

	public void setOptions(Set<Option> options) {
		this.options = options;
	}

}
